const { Schema, model } = require("mongoose");

const blogSchema = new Schema(
  {
    title: {
      type: String,
      required: true,
    },
    body: {
      type: String,
      required: true,
    },
    summary: {
      type: String,
      default: "",
    },
    coverImageURL: {
      type: String,
      required: false,
    },
    createdBy: {
      type: Schema.Types.ObjectId,
      ref: "user",
    },
    sourceUrl: {
      type: String,
      unique: true,
      sparse: true,
    },
    sourceName: {
      type: String,
      default: "",
    },
    sourcePublishedAt: {
      type: Date,
    },
    categories: {
      type: [String],
      default: [],
    },
    isAutoGenerated: {
      type: Boolean,
      default: false,
    },
  },
  { timestamps: true }
);

const Blog = model("blog", blogSchema);

module.exports = Blog;
